# Changes here will be overwritten by Copier
_commit: v0.0.3
_src_path: gh:shyndman/python-package-template
github_user: shyndman
module_name: lmnop_transcribe
package_name: lmnop-transcribe
project_name: lmnop:transcribe
python_version: '3.12'
user_email: scotty.hyndman@gmail.com
user_name: Scott Hyndman
