# The name of the audio device to use. Defaults to the system default.
audio_device_name = "default"
# The number of audio channels to record. Mono is recommended for transcription.
channels = 1
# The sample rate of the audio to record.
sample_rate = 22050
# The address of the Wyoming STT server.
wyoming_server_address = "0.0.0.0:10300"
# The minimum severity of log emitted by the tool
log_level = "DEBUG"

# The filename to save the recorded audio to.
filename = "output.wav"
# The block size to use when recording audio.
block_size = 8192

# Whether to use sox to detect silence.
use_sox_silence = true
# The amount of silence to trim from the beginning and end of the recording, in milliseconds.
trim_ms = 50
# The command to run to clean up the audio after recording.
audio_cleanup_command = ""

# The name of the xkeyboard device to use. Defaults to the system default.
keyboard_device_name = "default"
# The path to the sound to play when recording starts.
feedback_sound_start = "assets/start.mp3"
# The path to the sound to play when recording stops.
feedback_sound_stop = "assets/stop.mp3"
# Whether to use desktop notifications to alert the user when transcription is complete.
use_desktop_notifications = true

[trigger]
# The type of trigger to start recording (e.g., "caps_lock").
start_trigger_type = "caps_lock"
# Parameter for the start trigger (e.g., key code for a specific key).
start_trigger_param = ""
# The type of trigger to stop recording (e.g., "caps_lock").
stop_trigger_type = "caps_lock"
# Parameter for the stop trigger (e.g., key code for a specific key).
stop_trigger_param = ""
